#! /bin/sh

pkill stalonetray
pkill dunst
pkill eww
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend & 
feh --bg-scale Pictures/Wallpapers/wallpaper3.png
~/.repos/eww/target/release/eww open bar
dunst &
stalonetray --icon-size=32 --kludges=force_icons_size &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding 		56

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a "roblox_installer.exe" state=floating
bspc rule -a "robloxplayerlauncher.exe" state=floating
bspc rule -a "robloxstudiolauncherbeta.exe" state=floating
bpsc rule -a prismlauncher state=floating
